
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hacker_news_development

test:
  <<: *default
  database: hacker_news_test

production:
  <<: *default
  database: hacker_news_production
  username: hacker_news
  password: <%= ENV['HACKER_NEWS_DATABASE_PASSWORD'] %>
